### ISSUE TITLE
Several errors - Addon still maintained?

### ISSUE THREAD

**Issue by malvinas2** [scott967/script.extendedinfo#3]
Is this addon still maintained?

As described by @Fuchs246 [in the Kodi-Forum](https://forum.kodi.tv/showthread.php?tid=160558&pid=3201883#pid3201883), version 6.0.7 and Kodi Omega 21.1 throw up several error messages.
In addition to the ones mentioned by Fuchs2468, there is also the one listed below. 
It would be a pity, if the addon was no longer continued. 

```
2024-08-25 13:04:11.292 T:2804    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>' not supported between instances of 'str' and 'int'
                                                   Traceback (most recent call last):
                                                     File "C:\Program Files\Kodi21_1\portable_data\addons\script.extendedinfo\default.py", line 103, in <module>
                                                       Main()
                                                     File "C:\Program Files\Kodi21_1\portable_data\addons\script.extendedinfo\default.py", line 69, in __init__
                                                       listitems = process.start_info_actions(info, self.params)
                                                     File "C:\Program Files\Kodi21_1\portable_data\addons\script.extendedinfo\resources\lib\process.py", line 353, in start_info_actions
                                                       if result and result > -1:
                                                   TypeError: '>' not supported between instances of 'str' and 'int'
                                                   -->End of Python script error report<--
```

**EDIT:** 
Without having tried it: 
replace 
`if result and result > -1: `
with
`if bool(result and not result.isspace() and result != '-1'): `

(although I don't know what the '-1' is for, can the dialog even return 'Cancel'?)

**Comment by malvinas2** [comment]
Fixed in the Kodi-forum
